version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "coverage*"
      prod-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
