NTSC_RATE = 23.976
PAL_RATE = 25.0
NTSC_BROADCAST_RATE = 29.97

COMMAND_ATEMPO = "atempo"
COMMAND_ATEMPO_WITH = "atempo-with"
COMMAND_ATEMPO_VIDEO = "atempo-video"
COMMAND_DELAY = "delay"
COMMAND_HASTEN = "hasten"
COMMAND_EXTRACT = "extract"
COMMAND_APPEND = "append"
COMMAND_APPEND_SUBS = "subs"
